- upgrade release pipeline - update readme.md

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -5,17 +5,7 @@ on:
     types: [published]
 
 env:
-  # [avoid issue when Github action upgraded from 18.04 default to 20.04](https://github.com/aws/aws-cli/issues/5262)
-  AWS_EC2_METADATA_DISABLED: true
   REPO_NAME: openfaas
-  # Github account username (used for access github registry)
-  GH_USERNAME: magdabot
-  # Github Orgnisation name or user name for this repo
-  GH_ORGNAME: magda-io
-  #Docker Hub username
-  DH_USERNAME: magdabot
-  #S3 bucket name: this s3 bucket will be used to store published helm chart and index
-  S3_BUCKET: magda-charts
 
 jobs:
   release-helm-chart:
@@ -24,10 +14,16 @@ jobs:
     steps:
       - uses: actions/checkout@v2
 
-      - name: Use Node.js 12
+      - name: Use Node.js 14
         uses: actions/setup-node@v1
         with:
-          node-version: 12
+          node-version: 14
+
+      - name: Login to GitHub Container Registry
+        run: |
+          REPO_OWNER=`echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]'`
+          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
+
       - run: yarn install
       # - run: yarn build
       # - run: yarn test
@@ -41,39 +37,29 @@ jobs:
       - name: helm-chart-version-check
         run: yarn check-helm-chart-version deploy/${REPO_NAME}/Chart.yaml
 
-      # - name: Login to GitHub Package Repository
-      #   env:
-      #     GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
-      #   run: docker login docker.pkg.github.com -u ${GH_USERNAME} -p ${GH_TOKEN}
-
-      # - name: Build Docker Image & Push to Github Registry
-      #   run: yarn docker-build-prod --repository=docker.pkg.github.com/${GH_ORGNAME}/${REPO_NAME} --name=${REPO_NAME}
-
-      # - name: Login to Docker Hub
-      #   env:
-      #     DH_TOKEN: ${{ secrets.DOCKER_HUB_PASSWORD }}
-      #   run: docker login -u ${DH_USERNAME} -p ${DH_TOKEN}
-
-      # - name: Re-tag & Push Docker Image to Docker Hub
-      #   run: yarn retag-and-push --fromPrefix=docker.pkg.github.com/${GH_ORGNAME}/${REPO_NAME}/ --fromName=${REPO_NAME}
-
-      - name: Configure Git
+      - name: Check Helm Chart Document
         run: |
-          git config user.name "$GITHUB_ACTOR"
-          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
+          code=0
+          docker run --rm -v "$(pwd):/helm-docs" -u $(id -u) jnorwood/helm-docs:v1.5.0 -t ./README.md.gotmpl -o ../../README.md || code=$?;
+          if [ "$code" != "0" ]; then 
+            echo "Failed to run helm-docs!";
+            exit 1;
+          fi;
+          cd deploy
+          code=0
+          git ls-files -m | grep -i readme.md || code=$?;
+          if [ "$code" == "0" ]; then
+            echo -e "Some of helm chart docs are required to be updated using the [helm-docs](https://github.com/norwoodj/helm-docs) tool. \n
+            Please run helm-docs (v1.5.0) at project root, review & commit docs changes and push a new commit.";
+            exit 1;
+          else 
+            echo -e "helm docs check passed. helm docs update is not required.";
+          fi;
 
       - name: Release Helm Chart
-        env:
-          CR_TOKEN: "${{ secrets.GH_ACCESS_TOKEN }}"
-          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         run: |
+          REPO_OWNER=`echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]'`
           cd deploy
-          mkdir -p sync_dir
-          mkdir -p index_dir
-          if ! aws s3 cp s3://${S3_BUCKET}/index.yaml index_dir/index.yaml; then echo "failed to copy current repo index" && exit 1; fi
-          helm package -d sync_dir ${REPO_NAME}
-          helm repo index --merge "index_dir/index.yaml" sync_dir
-          mv -f sync_dir/index.yaml index_dir/index.yaml
-          aws s3 sync sync_dir s3://${S3_BUCKET}/
-          aws s3 cp index_dir/index.yaml s3://${S3_BUCKET}/index.yaml
+          helm package ${REPO_NAME}
+          PKG_NAME=`ls *.tgz`
+          helm push ${PKG_NAME} oci://ghcr.io/${REPO_OWNER}/charts
